version: '3.9'
services:
  nginx:
    build: ./nginx
    container_name: nginx-django-app
    ports:
      - 1337:80
    volumes:
      - ./volumes/staticfiles:/home/app/staticfiles
      - ./volumes/mediafiles:/home/app/mediafiles
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: ./web
    container_name: django-app
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn web.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./volumes/staticfiles:/home/app/staticfiles
      - ./volumes/mediafiles:/home/app/mediafiles

    expose:
      - 8000
    
    restart: "on-failure"